/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class collab_test_app_LightController */

#ifndef _Included_collab_test_app_LightController
#define _Included_collab_test_app_LightController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     collab_test_app_LightController
 * Method:    toggleLight
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_collab_test_app_LightController_toggleLight
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
