/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class collab_test_app_AirConditionerControl */

#ifndef _Included_collab_test_app_AirConditionerControl
#define _Included_collab_test_app_AirConditionerControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     collab_test_app_AirConditionerControl
 * Method:    toggleAirConditioner
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_collab_test_app_AirConditionerControl_toggleAirConditioner
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
