/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class collab_test_app_FanControl */

#ifndef _Included_collab_test_app_FanControl
#define _Included_collab_test_app_FanControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     collab_test_app_FanControl
 * Method:    setFanPosition
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_collab_test_app_FanControl_setFanPosition
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
